# Generated by Django 6.1 on 2026-09-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage_Data', '0015_alter_card_section_card_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_section',
            name='Card_Link',
            field=models.URLField(default='https://carekidney.onrender.com', max_length=500),
        ),
    ]
